-- outrip's real tables, pulled from the shared production project xowekqdsttxwbhfxvusa on
-- 2026-09-19 with the Supabase MCP (information_schema.columns, pg_constraint, pg_indexes,
-- pg_views, pg_trigger, pg_proc). Column types, defaults, CHECKs, foreign keys, the two
-- triggers and the three views are transcribed from that read, not from the repo.
--
-- OUTRIP HAS NO SUPABASE AUTH AND NO auth.users ROW. A buyer is an opaque uuid in an
-- HMAC-signed cookie, created silently at checkout (src/lib/buyer.ts). Nothing in this file
-- references auth.users, so this environment cannot collide with any other on the shared
-- stack. Its fixture ids are namespaced under ...0000000f10xx anyway (rule 11).

create table if not exists outrip_buyers (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz not null default now(),
  dry_streak    integer not null default 0,
  dust          integer not null default 0,
  email         text,
  last_seen_at  timestamptz
);
create index if not exists outrip_buyers_email_idx on outrip_buyers (lower(email));

create table if not exists outrip_products (
  domain          text primary key,
  tagline         text,
  created_at      timestamptz not null default now(),
  packs_opened    integer not null default 0,
  reach           integer not null default 0,
  dry_streak      integer not null default 0,
  dust            integer not null default 0,
  url             text not null,
  owner_buyer_id  uuid references outrip_buyers(id),
  constraint outrip_products_url_is_real check (
    url ~ '^https?://[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+(:[0-9]+)?(/.*)?$'
  )
);
create index if not exists outrip_products_owner_idx on outrip_products (owner_buyer_id);

create table if not exists outrip_pulls (
  id          bigint generated by default as identity primary key,
  domain      text not null references outrip_products(domain) on delete cascade,
  pull_index  integer not null,
  species     text not null,
  chroma      text not null,
  eyes        text not null,
  mark        text not null,
  cut         text not null,
  serial      text not null,
  rating      numeric not null,
  tier        smallint not null,
  minted_at   timestamptz not null default now(),
  traded_in   boolean not null default false,
  buyer_id    uuid references outrip_buyers(id),
  constraint outrip_pulls_domain_pull_index_key unique (domain, pull_index)
);
create index if not exists outrip_pulls_buyer_idx on outrip_pulls (buyer_id, rating desc) where not traded_in;
create index if not exists outrip_pulls_domain_rating_idx on outrip_pulls (domain, rating desc) where not traded_in;
create index if not exists outrip_pulls_minted_idx on outrip_pulls (minted_at desc);
create index if not exists outrip_pulls_minted_live_idx on outrip_pulls (minted_at desc) where not traded_in;
create index if not exists outrip_pulls_minted_asc_idx on outrip_pulls (minted_at, id) where not traded_in;
create index if not exists outrip_pulls_rating_idx on outrip_pulls (rating desc) where not traded_in;

create table if not exists outrip_orders (
  id                     uuid primary key default gen_random_uuid(),
  domain                 text not null,
  pack_id                text not null,
  packs                  integer not null check (packs > 0),
  cards                  integer not null check (cards > 0),
  amount_cents           integer not null check (amount_cents >= 0),
  currency               text not null default 'usd',
  stripe_session_id      text unique,
  stripe_payment_intent  text,
  status                 text not null default 'pending'
                         check (status in ('pending', 'paid', 'opened', 'refunded')),
  first_pull_index       integer,
  created_at             timestamptz not null default now(),
  paid_at                timestamptz,
  opened_at              timestamptz,
  refunded_at            timestamptz,
  stripe_session_url     text,
  buyer_id               uuid references outrip_buyers(id),
  line                   text not null default 'core' check (line in ('core', 'tools'))
);
create index if not exists outrip_orders_buyer_idx on outrip_orders (buyer_id);
create index if not exists outrip_orders_domain_idx on outrip_orders (domain);
create index if not exists outrip_orders_domain_status_created_idx on outrip_orders (domain, status, created_at desc);
create index if not exists outrip_orders_payment_intent_idx on outrip_orders (stripe_payment_intent) where stripe_payment_intent is not null;
create index if not exists outrip_orders_pending_created_idx on outrip_orders (created_at desc) where status = 'pending';
create index if not exists outrip_orders_status_idx on outrip_orders (status);

create table if not exists outrip_shop_stock (
  id          bigint generated by default as identity primary key,
  species     text not null,
  chroma      text not null,
  eyes        text not null,
  mark        text not null,
  cut         text not null,
  serial      text not null,
  rating      numeric not null,
  tier        smallint not null check (tier <= 4),
  stock       integer not null default 1 check (stock >= 0),
  restocks_to integer not null default 1,
  created_at  timestamptz not null default now()
);

create table if not exists outrip_dust_ledger (
  id          bigint generated by default as identity primary key,
  domain      text references outrip_products(domain) on delete cascade,
  delta       integer not null,
  reason      text not null check (reason in ('trade_in', 'shop_buy', 'grant', 'trade_in_tool')),
  pull_index  integer,
  shop_id     bigint references outrip_shop_stock(id),
  created_at  timestamptz not null default now(),
  buyer_id    uuid references outrip_buyers(id)
);
create index if not exists outrip_dust_ledger_buyer_idx on outrip_dust_ledger (buyer_id);
create index if not exists outrip_dust_ledger_domain_idx on outrip_dust_ledger (domain);
create index if not exists outrip_dust_ledger_shop_id_idx on outrip_dust_ledger (shop_id) where shop_id is not null;

create table if not exists outrip_clicks (
  id          bigint generated by default as identity primary key,
  domain      text not null references outrip_products(domain) on delete cascade,
  pull_index  integer,
  source      text,
  created_at  timestamptz not null default now(),
  ip_hash     text
);
create index if not exists outrip_clicks_dedup_idx on outrip_clicks (domain, ip_hash, created_at desc);
create index if not exists outrip_clicks_domain_idx on outrip_clicks (domain, created_at desc);

create table if not exists outrip_takeover_log (
  id          bigint generated by default as identity primary key,
  domain      text not null,
  pull_index  integer not null,
  rating      numeric not null,
  tier        integer not null,
  minted_at   timestamptz not null,
  constraint outrip_takeover_log_domain_pull_index_key unique (domain, pull_index),
  constraint outrip_takeover_log_pull_fkey foreign key (domain, pull_index)
    references outrip_pulls(domain, pull_index) on delete cascade
);
create index if not exists outrip_takeover_log_minted_idx on outrip_takeover_log (minted_at desc);

-- The Tool Vault line. Present so the schema is the product's, and so `not_gradable` can say
-- truthfully that its catalogue is filled by a nightly ToolDrift refresh this fixture does not
-- carry, rather than that the tables are missing.
create table if not exists outrip_tool_cards (
  id               bigint generated by default as identity primary key,
  kind             text not null check (kind in ('tool', 'model')),
  slug             text not null,
  name             text not null,
  vendor           text,
  layer            text,
  tooldrift_url    text not null,
  adoption_metric  text not null check (adoption_metric in
                     ('openrouter_model_share', 'openrouter_tokens_week', 'github_stars', 'unmeasured')),
  adoption_value   numeric,
  adoption_line    text not null,
  adoption_rank    integer not null,
  cohort_size      integer not null,
  tier             smallint not null,
  rating           numeric not null,
  is_chase         boolean not null default false,
  flavor           text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint outrip_tool_cards_kind_slug_key unique (kind, slug)
);
create index if not exists outrip_tool_cards_rating_idx on outrip_tool_cards (rating desc);
create index if not exists outrip_tool_cards_tier_idx on outrip_tool_cards (tier);

create table if not exists outrip_tool_pulls (
  id           bigint generated by default as identity primary key,
  order_id     uuid references outrip_orders(id) on delete set null,
  buyer_id     uuid references outrip_buyers(id) on delete cascade,
  card_id      bigint not null references outrip_tool_cards(id),
  mint_serial  integer not null,
  pulled_at    timestamptz not null default now(),
  traded_in    boolean not null default false
);
create index if not exists outrip_tool_pulls_buyer_idx on outrip_tool_pulls (buyer_id, traded_in);
create index if not exists outrip_tool_pulls_card_idx on outrip_tool_pulls (card_id);

create table if not exists outrip_tool_card_moves (
  id           bigint generated by default as identity primary key,
  card_id      bigint not null references outrip_tool_cards(id) on delete cascade,
  from_tier    smallint,
  to_tier      smallint,
  from_rating  numeric,
  to_rating    numeric,
  from_rank    integer,
  to_rank      integer,
  reason       text not null,
  moved_at     timestamptz not null default now()
);
create index if not exists outrip_tool_card_moves_card_idx on outrip_tool_card_moves (card_id, moved_at desc);

/* ═══════════════════════════════════════════════════════════════════════════════
   FUNCTIONS AND TRIGGERS, verbatim from pg_get_functiondef / pg_get_triggerdef.

   outrip_record_click is the whole of the /out/<domain> route. It dedups on the hashed
   client, inserts the ledger row and increments outrip_products.reach in ONE statement, which
   is why the counter the buyer reads and the rows behind it cannot drift apart. The Reach
   task grades exactly that equality.
   ═══════════════════════════════════════════════════════════════════════════════ */

create or replace function public.outrip_record_click(
  d text, p integer default null, s text default null, h text default null,
  window_minutes integer default 30)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if h is not null and exists (
       select 1 from outrip_clicks
        where domain = d and ip_hash = h
          and created_at > now() - make_interval(mins => window_minutes)) then
    return false;
  end if;
  insert into outrip_clicks (domain, pull_index, source, ip_hash) values (d, p, s, h);
  update outrip_products set reach = coalesce(reach, 0) + 1 where domain = d;
  return true;
end;
$function$;

create or replace function public.outrip_note_takeover()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if not new.traded_in
     and new.rating > coalesce((select max(rating) from outrip_takeover_log), -1) then
    insert into outrip_takeover_log (domain, pull_index, rating, tier, minted_at)
    values (new.domain, new.pull_index, new.rating, new.tier, new.minted_at)
    on conflict (domain, pull_index) do nothing;
  end if;
  return new;
exception when others then
  raise warning 'outrip_note_takeover skipped for %/%: %', new.domain, new.pull_index, sqlerrm;
  return new;
end;
$function$;

create or replace function public.outrip_unnote_takeover()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if new.traded_in and not old.traded_in then
    delete from outrip_takeover_log
     where domain = new.domain and pull_index = new.pull_index;
  end if;
  return new;
exception when others then
  raise warning 'outrip_unnote_takeover skipped: %', sqlerrm;
  return new;
end;
$function$;

drop trigger if exists outrip_pulls_takeover on outrip_pulls;
create trigger outrip_pulls_takeover after insert on public.outrip_pulls
  for each row execute function outrip_note_takeover();

drop trigger if exists outrip_pulls_untakeover on outrip_pulls;
create trigger outrip_pulls_untakeover after update of traded_in on public.outrip_pulls
  for each row execute function outrip_unnote_takeover();

/* ═══════════════════════════════════════════════════════════════════════════════
   THE VIEWS. The board is a VIEW, which is why a grader never has to recompute a rank.
   outrip_board takes the best NON-TRADED pull per product, so a refund or a trade-in moves
   the rank by itself the moment traded_in flips.
   ═══════════════════════════════════════════════════════════════════════════════ */

create or replace view outrip_board as
  select p.domain, p.tagline, p.url, p.reach, p.packs_opened, p.created_at,
         b.rating as best_rating, b.tier as best_tier, b.pull_index as best_pull,
         b.species, b.chroma, b.eyes, b.mark, b.cut, b.serial,
         b.minted_at as best_minted_at,
         rank() over (order by b.rating desc) as rank
    from outrip_products p
    join lateral (
      select x.* from outrip_pulls x
       where x.domain = p.domain and not x.traded_in
       order by x.rating desc, x.pull_index
       limit 1) b on true;

create or replace view outrip_board_24h as
  select p.domain, b.rating as best_rating_24h, rank() over (order by b.rating desc) as rank_24h
    from outrip_products p
    join lateral (
      select x.rating from outrip_pulls x
       where x.domain = p.domain and not x.traded_in and x.minted_at <= (now() - interval '24:00:00')
       order by x.rating desc
       limit 1) b on true;

create or replace view outrip_recent as
  select r.domain, p.tagline, p.url, r.pull_index, r.species, r.chroma, r.eyes, r.mark, r.cut,
         r.serial, r.rating, r.tier, r.minted_at,
         (r.rating >= (select max(x.rating) from outrip_pulls x
                        where x.domain = r.domain and not x.traded_in)) as is_best
    from (select distinct on (k.domain) k.*
            from (select * from outrip_pulls where not traded_in
                   order by minted_at desc limit 400) k
           order by k.domain, k.minted_at desc) r
    join outrip_products p on p.domain = r.domain;

create or replace view outrip_takeovers as
  select domain, pull_index, rating, tier, minted_at, id
    from outrip_takeover_log
   order by minted_at desc, id desc;
