-- GENERATED by scripts/make-seed.mjs on 2026-09-20T03:17:50.917Z. Do not hand-edit.
-- Every state, date, quote and offset below was produced by the product's own
-- parseDoc/readContract/evaluate over fixtures/contracts.mjs, evaluated against 2026-09-20.
--
-- Applied before every episode. TRUNCATE plus INSERT, and it touches only cw_ tables, so it
-- shares the estate's one local stack with every other product's fixture.

truncate table cw_events, cw_notices, cw_signals, cw_runs, cw_clauses, cw_contracts,
               cw_entitlements, cw_members, cw_orgs restart identity cascade;

-- == the two tenants ====================================================================
-- DUNMERE STOPPED PAYING, AND NOTHING ABOUT ITS ROWS SAYS SO. `plan` still reads 'standard'
-- because Stripe's customer.subscription.deleted moves billing_status and never touches plan.
-- isEntitled() is the PAIR, so this org is out, and the outbox sweep withholds its mail
-- rather than cancelling it.
insert into cw_orgs (id, name, plan, billing_status, is_demo, notice_from, created_at) values
  ('00000000-0000-4000-8000-000000000001', 'Harborline Logistics', 'standard', 'active',   false, 'desk@harborlinelogistics.example', now() - interval '400 days'),
  ('00000000-0000-4000-8000-000000000002', 'Dunmere Cold Chain', 'standard', 'canceled', false, 'desk@dunmerecoldchain.example', now() - interval '330 days');

-- The desk's own login. requireMember() reads exactly this row and derives the org id from
-- it; nothing downstream ever takes an org from the client.
insert into cw_members (id, user_id, org_id, email, role, created_at) values
  ('00000000-0000-4000-8000-0000000c0002', '00000000-0000-4000-8000-0000000c0001', '00000000-0000-4000-8000-000000000001', 'desk@harborlinelogistics.example', 'owner', now() - interval '400 days');

insert into cw_entitlements (email, org_id, plan, billing_status, claimed_by, claimed_at) values
  ('desk@harborlinelogistics.example', '00000000-0000-4000-8000-000000000001', 'standard', 'active', '00000000-0000-4000-8000-0000000c0001', now() - interval '400 days');

-- == the book ===========================================================================
-- Yard Handling Agreement / Pellworth Freight Systems: closing, notice by 2026-09-23
insert into cw_contracts (id, org_id, title, counterparty, source, file_name, page_count, page_starts, doc_text, watched, uploaded_at, last_read_at, last_state, term_end, notice_days, auto_renews, notice_deadline, blocked_by) values
  ('00000000-0000-4000-8000-000000001101', '00000000-0000-4000-8000-000000000001', 'Yard Handling Agreement', 'Pellworth Freight Systems', 'upload', 'pellworth-yard-handling.pdf', 1, '{0}'::integer[], 'This Agreement is effective as of November 19, 2024.

The initial term ends on November 22, 2026.

Either party may prevent renewal by giving written notice of non-renewal not less than sixty (60) days prior to the end of the then-current term.

This Agreement shall automatically renew for successive twelve (12) month terms.

Fees may increase by no more than 4 percent (4%) on each renewal.

Each party shall perform its obligations in good faith and in accordance with applicable law.

Neither party may assign this Agreement without the prior written consent of the other.

This Agreement is governed by the laws of the State of Washington.

', true, now() - interval '30 days', now() - interval '9 hours', 'closing', '2026-11-22', 60, true, '2026-09-23', '{}'::text[]);
-- Terminal Access Agreement / Pellworth Freight Systems: approaching, notice by 2026-10-20
insert into cw_contracts (id, org_id, title, counterparty, source, file_name, page_count, page_starts, doc_text, watched, uploaded_at, last_read_at, last_state, term_end, notice_days, auto_renews, notice_deadline, blocked_by) values
  ('00000000-0000-4000-8000-000000001102', '00000000-0000-4000-8000-000000000001', 'Terminal Access Agreement', 'Pellworth Freight Systems', 'upload', 'pellworth-terminal-access.pdf', 1, '{0}'::integer[], 'This Agreement is effective as of August 16, 2025.

The initial term ends on January 18, 2027.

Either party may prevent renewal by giving written notice of non-renewal not less than ninety (90) days prior to the end of the then-current term.

This Agreement shall automatically renew for successive twelve (12) month terms.

Fees may increase by no more than 3 percent (3%) on each renewal.

Each party shall perform its obligations in good faith and in accordance with applicable law.

Neither party may assign this Agreement without the prior written consent of the other.

This Agreement is governed by the laws of the State of Washington.

', true, now() - interval '30 days', now() - interval '9 hours', 'approaching', '2027-01-18', 90, true, '2026-10-20', '{}'::text[]);
-- Site Services Agreement / Rothbury Group: unknown
insert into cw_contracts (id, org_id, title, counterparty, source, file_name, page_count, page_starts, doc_text, watched, uploaded_at, last_read_at, last_state, term_end, notice_days, auto_renews, notice_deadline, blocked_by) values
  ('00000000-0000-4000-8000-000000001103', '00000000-0000-4000-8000-000000000001', 'Site Services Agreement', 'Rothbury Group', 'upload', 'rothbury-site-services.pdf', 1, '{0}'::integer[], 'The term of this Agreement commences on May 8, 2025 and continues until terminated by either party.

Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.

This Agreement shall automatically renew for successive twelve (12) month terms.

Fees may increase by no more than 5 percent (5%) on each renewal.

Each party shall perform its obligations in good faith and in accordance with applicable law.

Neither party may assign this Agreement without the prior written consent of the other.

This Agreement is governed by the laws of the State of Washington.

', true, now() - interval '30 days', now() - interval '9 hours', 'unknown', null, 30, true, null, '{"term_end"}'::text[]);
-- Brine Supply Agreement / Ostergaard Marine: closing, notice by 2026-09-25
insert into cw_contracts (id, org_id, title, counterparty, source, file_name, page_count, page_starts, doc_text, watched, uploaded_at, last_read_at, last_state, term_end, notice_days, auto_renews, notice_deadline, blocked_by) values
  ('00000000-0000-4000-8000-000000001104', '00000000-0000-4000-8000-000000000001', 'Brine Supply Agreement', 'Ostergaard Marine', 'upload', 'ostergaard-brine-supply.pdf', 1, '{0}'::integer[], 'This Agreement is effective as of September 5, 2025.

The initial term ends on November 9, 2026.

Either party may prevent renewal by giving written notice of non-renewal not less than forty-five (45) days prior to the end of the then-current term.

This Agreement shall automatically renew for successive twelve (12) month terms.

Fees may increase by no more than 6 percent (6%) on each renewal.

Each party shall perform its obligations in good faith and in accordance with applicable law.

Neither party may assign this Agreement without the prior written consent of the other.

This Agreement is governed by the laws of the State of Washington.

', true, now() - interval '30 days', now() - interval '9 hours', 'closing', '2026-11-09', 45, true, '2026-09-25', '{}'::text[]);
-- Depot Cleaning Agreement / Kessler Facility Services: approaching, notice by 2026-09-30
insert into cw_contracts (id, org_id, title, counterparty, source, file_name, page_count, page_starts, doc_text, watched, uploaded_at, last_read_at, last_state, term_end, notice_days, auto_renews, notice_deadline, blocked_by) values
  ('00000000-0000-4000-8000-000000001105', '00000000-0000-4000-8000-000000000001', 'Depot Cleaning Agreement', 'Kessler Facility Services', 'upload', 'kessler-depot-cleaning.pdf', 1, '{0}'::integer[], 'This Agreement is effective as of August 21, 2025.

The initial term ends on October 30, 2026.

Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.

This Agreement shall automatically renew for successive twelve (12) month terms.

Fees may increase by no more than 2 percent (2%) on each renewal.

Each party shall perform its obligations in good faith and in accordance with applicable law.

Neither party may assign this Agreement without the prior written consent of the other.

This Agreement is governed by the laws of the State of Washington.

', true, now() - interval '30 days', now() - interval '9 hours', 'approaching', '2026-10-30', 30, true, '2026-09-30', '{}'::text[]);
-- Haulage Framework Agreement / Marwood Transport: approaching, notice by 2026-10-04
insert into cw_contracts (id, org_id, title, counterparty, source, file_name, page_count, page_starts, doc_text, watched, uploaded_at, last_read_at, last_state, term_end, notice_days, auto_renews, notice_deadline, blocked_by) values
  ('00000000-0000-4000-8000-000000001106', '00000000-0000-4000-8000-000000000002', 'Haulage Framework Agreement', 'Marwood Transport', 'upload', 'marwood-haulage-framework.pdf', 1, '{0}'::integer[], 'This Agreement is effective as of November 4, 2025.

The initial term ends on November 3, 2026.

Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.

This Agreement shall automatically renew for successive twelve (12) month terms.

Fees may increase by no more than 4 percent (4%) on each renewal.

Each party shall perform its obligations in good faith and in accordance with applicable law.

Neither party may assign this Agreement without the prior written consent of the other.

This Agreement is governed by the laws of the State of Washington.

', true, now() - interval '30 days', now() - interval '9 hours', 'approaching', '2026-11-03', 30, true, '2026-10-04', '{}'::text[]);

-- == every clause the reader located, and every one it refused to =======================
-- THESE ARE clauseRow()'s OWN TWO SHAPES. A found clause carries a value AND a span AND the
-- bytes at that span; a miss carries a reason and nothing else. The CHECK constraint in
-- 01-schema.sql rejects anything in between, which is the database saying what locate.ts's
-- verify() says.
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001101', 'effective_date', true, '{"type":"date","iso":"2024-11-19"}'::jsonb, 1, 0, 52, 'This Agreement is effective as of November 19, 2024.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001101', 'term_end', true, '{"type":"date","iso":"2026-11-22"}'::jsonb, 1, 54, 97, 'The initial term ends on November 22, 2026.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001101', 'notice_period', true, '{"type":"days","days":60}'::jsonb, 1, 99, 244, 'Either party may prevent renewal by giving written notice of non-renewal not less than sixty (60) days prior to the end of the then-current term.', 'day-count', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001101', 'auto_renew', true, '{"type":"flag","on":true,"termLabel":"twelve (12) month"}'::jsonb, 1, 246, 326, 'This Agreement shall automatically renew for successive twelve (12) month terms.', 'auto-renew', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001101', 'price_increase', true, '{"type":"percent","percent":4}'::jsonb, 1, 328, 393, 'Fees may increase by no more than 4 percent (4%) on each renewal.', 'percent', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001102', 'effective_date', true, '{"type":"date","iso":"2025-08-16"}'::jsonb, 1, 0, 50, 'This Agreement is effective as of August 16, 2025.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001102', 'term_end', true, '{"type":"date","iso":"2027-01-18"}'::jsonb, 1, 52, 94, 'The initial term ends on January 18, 2027.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001102', 'notice_period', true, '{"type":"days","days":90}'::jsonb, 1, 96, 242, 'Either party may prevent renewal by giving written notice of non-renewal not less than ninety (90) days prior to the end of the then-current term.', 'day-count', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001102', 'auto_renew', true, '{"type":"flag","on":true,"termLabel":"twelve (12) month"}'::jsonb, 1, 244, 324, 'This Agreement shall automatically renew for successive twelve (12) month terms.', 'auto-renew', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001102', 'price_increase', true, '{"type":"percent","percent":3}'::jsonb, 1, 326, 391, 'Fees may increase by no more than 3 percent (3%) on each renewal.', 'percent', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001103', 'effective_date', true, '{"type":"date","iso":"2025-05-08"}'::jsonb, 1, 0, 99, 'The term of this Agreement commences on May 8, 2025 and continues until terminated by either party.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001103', 'term_end', false, null, null, null, null, null, null, 'clause-present-no-value', now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001103', 'notice_period', true, '{"type":"days","days":30}'::jsonb, 1, 101, 247, 'Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.', 'day-count', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001103', 'auto_renew', true, '{"type":"flag","on":true,"termLabel":"twelve (12) month"}'::jsonb, 1, 249, 329, 'This Agreement shall automatically renew for successive twelve (12) month terms.', 'auto-renew', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001103', 'price_increase', true, '{"type":"percent","percent":5}'::jsonb, 1, 331, 396, 'Fees may increase by no more than 5 percent (5%) on each renewal.', 'percent', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', 'effective_date', true, '{"type":"date","iso":"2025-09-05"}'::jsonb, 1, 0, 52, 'This Agreement is effective as of September 5, 2025.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', 'term_end', true, '{"type":"date","iso":"2026-11-09"}'::jsonb, 1, 54, 96, 'The initial term ends on November 9, 2026.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', 'notice_period', true, '{"type":"days","days":45}'::jsonb, 1, 98, 248, 'Either party may prevent renewal by giving written notice of non-renewal not less than forty-five (45) days prior to the end of the then-current term.', 'day-count', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', 'auto_renew', true, '{"type":"flag","on":true,"termLabel":"twelve (12) month"}'::jsonb, 1, 250, 330, 'This Agreement shall automatically renew for successive twelve (12) month terms.', 'auto-renew', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', 'price_increase', true, '{"type":"percent","percent":6}'::jsonb, 1, 332, 397, 'Fees may increase by no more than 6 percent (6%) on each renewal.', 'percent', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', 'effective_date', true, '{"type":"date","iso":"2025-08-21"}'::jsonb, 1, 0, 50, 'This Agreement is effective as of August 21, 2025.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', 'term_end', true, '{"type":"date","iso":"2026-10-30"}'::jsonb, 1, 52, 94, 'The initial term ends on October 30, 2026.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', 'notice_period', true, '{"type":"days","days":30}'::jsonb, 1, 96, 242, 'Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.', 'day-count', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', 'auto_renew', true, '{"type":"flag","on":true,"termLabel":"twelve (12) month"}'::jsonb, 1, 244, 324, 'This Agreement shall automatically renew for successive twelve (12) month terms.', 'auto-renew', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', 'price_increase', true, '{"type":"percent","percent":2}'::jsonb, 1, 326, 391, 'Fees may increase by no more than 2 percent (2%) on each renewal.', 'percent', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', 'effective_date', true, '{"type":"date","iso":"2025-11-04"}'::jsonb, 1, 0, 51, 'This Agreement is effective as of November 4, 2025.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', 'term_end', true, '{"type":"date","iso":"2026-11-03"}'::jsonb, 1, 53, 95, 'The initial term ends on November 3, 2026.', 'month-day-year', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', 'notice_period', true, '{"type":"days","days":30}'::jsonb, 1, 97, 243, 'Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.', 'day-count', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', 'auto_renew', true, '{"type":"flag","on":true,"termLabel":"twelve (12) month"}'::jsonb, 1, 245, 325, 'This Agreement shall automatically renew for successive twelve (12) month terms.', 'auto-renew', null, now() - interval '9 hours');
insert into cw_clauses (org_id, contract_id, kind, found, value_json, span_page, span_start, span_end, quote, pattern, not_found_reason, read_at) values
  ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', 'price_increase', true, '{"type":"percent","percent":4}'::jsonb, 1, 327, 392, 'Fees may increase by no more than 4 percent (4%) on each renewal.', 'percent', null, now() - interval '9 hours');

-- == last night's pass ==================================================================
insert into cw_runs (id, org_id, today, started_at, finished_at, contracts_read, clauses_read, clauses_not_found, signals_raised, capped) values
  ('00000000-0000-4000-8000-000000002101', '00000000-0000-4000-8000-000000000001', '2026-09-20', now() - interval '9 hours', now() - interval '8 hours 58 minutes', 5, 25, 1, 5, false);
insert into cw_runs (id, org_id, today, started_at, finished_at, contracts_read, clauses_read, clauses_not_found, signals_raised, capped) values
  ('00000000-0000-4000-8000-000000002102', '00000000-0000-4000-8000-000000000002', '2026-09-20', now() - interval '9 hours', now() - interval '8 hours 58 minutes', 1, 5, 0, 1, false);

-- == the morning queue ==================================================================
-- Yard Handling Agreement: approaching to closing, open
insert into cw_signals (id, org_id, contract_id, run_id, kind, clause_kind, state_from, state_to, due_date, quote, span_page, span_start, span_end, status, raised_at, resolved_at) values
  ('00000000-0000-4000-8000-000000003101', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001101', '00000000-0000-4000-8000-000000002101', 'state_change', 'notice_period', 'approaching', 'closing', '2026-09-23', 'Either party may prevent renewal by giving written notice of non-renewal not less than sixty (60) days prior to the end of the then-current term.', 1, 99, 244, 'open', now() - interval '9 hours', null);
-- Terminal Access Agreement: clear to approaching, open
insert into cw_signals (id, org_id, contract_id, run_id, kind, clause_kind, state_from, state_to, due_date, quote, span_page, span_start, span_end, status, raised_at, resolved_at) values
  ('00000000-0000-4000-8000-000000003102', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001102', '00000000-0000-4000-8000-000000002101', 'state_change', 'notice_period', 'clear', 'approaching', '2026-10-20', 'Either party may prevent renewal by giving written notice of non-renewal not less than ninety (90) days prior to the end of the then-current term.', 1, 96, 242, 'open', now() - interval '9 hours', null);
-- Site Services Agreement: first read to unknown, open, NO QUOTE
insert into cw_signals (id, org_id, contract_id, run_id, kind, clause_kind, state_from, state_to, due_date, quote, span_page, span_start, span_end, status, raised_at, resolved_at) values
  ('00000000-0000-4000-8000-000000003103', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001103', '00000000-0000-4000-8000-000000002101', 'state_change', 'term_end', null, 'unknown', null, null, null, null, null, 'open', now() - interval '9 hours', null);
-- Brine Supply Agreement: approaching to closing, approved
insert into cw_signals (id, org_id, contract_id, run_id, kind, clause_kind, state_from, state_to, due_date, quote, span_page, span_start, span_end, status, raised_at, resolved_at) values
  ('00000000-0000-4000-8000-000000003104', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', '00000000-0000-4000-8000-000000002101', 'state_change', 'notice_period', 'approaching', 'closing', '2026-09-25', 'Either party may prevent renewal by giving written notice of non-renewal not less than forty-five (45) days prior to the end of the then-current term.', 1, 98, 248, 'approved', now() - interval '9 hours', now() - interval '20 minutes');
-- Depot Cleaning Agreement: clear to approaching, approved
insert into cw_signals (id, org_id, contract_id, run_id, kind, clause_kind, state_from, state_to, due_date, quote, span_page, span_start, span_end, status, raised_at, resolved_at) values
  ('00000000-0000-4000-8000-000000003105', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', '00000000-0000-4000-8000-000000002101', 'state_change', 'notice_period', 'clear', 'approaching', '2026-09-30', 'Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.', 1, 96, 242, 'approved', now() - interval '9 hours', now() - interval '20 minutes');
-- Haulage Framework Agreement: clear to approaching, approved
insert into cw_signals (id, org_id, contract_id, run_id, kind, clause_kind, state_from, state_to, due_date, quote, span_page, span_start, span_end, status, raised_at, resolved_at) values
  ('00000000-0000-4000-8000-000000003106', '00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', '00000000-0000-4000-8000-000000002102', 'state_change', 'notice_period', 'clear', 'approaching', '2026-10-04', 'Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.', 1, 97, 243, 'approved', now() - interval '9 hours', now() - interval '20 minutes');

-- == the outbox ========================================================================
-- EVERY ROW HERE IS WHAT schedule() WRITES, INCLUDING THE ARITHMETIC. send_after is
-- created_at plus UNDO_WINDOW_SECONDS (90), and the dispatcher's own WHERE clause is
-- `state = 'scheduled' and send_after <= now()`, so the first of these three is invisible to
-- a sweep and the other two are due. The window is relative to the RESET, not to the day this
-- file was generated: an absolute instant would have elapsed by the second episode.
-- Brine Supply Agreement, Harborline Logistics
insert into cw_notices (id, org_id, contract_id, signal_id, channel, to_addr, subject, body, state, send_after, sent_at, cancelled_at, evidence, created_at) values
  ('00000000-0000-4000-8000-000000004101', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', '00000000-0000-4000-8000-000000003104', 'email', 'desk@harborlinelogistics.example', 'Notice of non-renewal — Brine Supply Agreement', 'Ostergaard Marine,

This is written notice that Harborline Logistics does not intend to renew Brine Supply Agreement, which ends on 2026-11-09.

The agreement requires notice by 2026-09-25. This notice is given within that period.

For reference, the clause this notice is given under reads:

  "Either party may prevent renewal by giving written notice of non-renewal not less than forty-five (45) days prior to the end of the then-current term."

Harborline Logistics', 'scheduled', now() + interval '90 seconds', null, null, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than forty-five (45) days prior to the end of the then-current term.","page":1,"start":98,"end":248,"clauseKind":"notice_period"}'::jsonb, now() - interval '1 second');
-- Depot Cleaning Agreement, Harborline Logistics
insert into cw_notices (id, org_id, contract_id, signal_id, channel, to_addr, subject, body, state, send_after, sent_at, cancelled_at, evidence, created_at) values
  ('00000000-0000-4000-8000-000000004102', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', '00000000-0000-4000-8000-000000003105', 'email', 'desk@harborlinelogistics.example', 'Notice of non-renewal — Depot Cleaning Agreement', 'Kessler Facility Services,

This is written notice that Harborline Logistics does not intend to renew Depot Cleaning Agreement, which ends on 2026-10-30.

The agreement requires notice by 2026-09-30. This notice is given within that period.

For reference, the clause this notice is given under reads:

  "Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term."

Harborline Logistics', 'scheduled', now() - interval '11 minutes', null, null, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.","page":1,"start":96,"end":242,"clauseKind":"notice_period"}'::jsonb, now() - interval '12 minutes 30 seconds');
-- Haulage Framework Agreement, Dunmere Cold Chain
insert into cw_notices (id, org_id, contract_id, signal_id, channel, to_addr, subject, body, state, send_after, sent_at, cancelled_at, evidence, created_at) values
  ('00000000-0000-4000-8000-000000004103', '00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', '00000000-0000-4000-8000-000000003106', 'email', 'desk@dunmerecoldchain.example', 'Notice of non-renewal — Haulage Framework Agreement', 'Marwood Transport,

This is written notice that Dunmere Cold Chain does not intend to renew Haulage Framework Agreement, which ends on 2026-11-03.

The agreement requires notice by 2026-10-04. This notice is given within that period.

For reference, the clause this notice is given under reads:

  "Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term."

Dunmere Cold Chain', 'scheduled', now() - interval '14 minutes', null, null, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.","page":1,"start":97,"end":243,"clauseKind":"notice_period"}'::jsonb, now() - interval '15 minutes 30 seconds');

-- == the record ========================================================================
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001101', '00000000-0000-4000-8000-000000003101', 'state_change', 'Yard Handling Agreement: Notice window open → Notice window closing', 'Notice deadline 2026-09-23 · term ends 2026-11-22', true, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than sixty (60) days prior to the end of the then-current term.","page":1,"start":99,"end":244}'::jsonb, now() - interval '9 hours');
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001102', '00000000-0000-4000-8000-000000003102', 'state_change', 'Terminal Access Agreement: Clear → Notice window open', 'Notice deadline 2026-10-20 · term ends 2027-01-18', false, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than ninety (90) days prior to the end of the then-current term.","page":1,"start":96,"end":242}'::jsonb, now() - interval '9 hours');
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001103', '00000000-0000-4000-8000-000000003103', 'not_found', 'Site Services Agreement — not found', 'Not found: term ends. No date was asserted.', false, '{}'::jsonb, now() - interval '9 hours');
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', '00000000-0000-4000-8000-000000003104', 'state_change', 'Brine Supply Agreement: Notice window open → Notice window closing', 'Notice deadline 2026-09-25 · term ends 2026-11-09', true, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than forty-five (45) days prior to the end of the then-current term.","page":1,"start":98,"end":248}'::jsonb, now() - interval '9 hours');
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', '00000000-0000-4000-8000-000000003105', 'state_change', 'Depot Cleaning Agreement: Clear → Notice window open', 'Notice deadline 2026-09-30 · term ends 2026-10-30', false, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.","page":1,"start":96,"end":242}'::jsonb, now() - interval '9 hours');
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', '00000000-0000-4000-8000-000000003106', 'state_change', 'Haulage Framework Agreement: Clear → Notice window open', 'Notice deadline 2026-10-04 · term ends 2026-11-03', false, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.","page":1,"start":97,"end":243}'::jsonb, now() - interval '9 hours');
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001104', '00000000-0000-4000-8000-000000003104', 'notice_scheduled', 'Notice queued — Notice of non-renewal — Brine Supply Agreement', 'Goes out in 90s unless killed.', false, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than forty-five (45) days prior to the end of the then-current term.","page":1,"start":98,"end":248,"clauseKind":"notice_period"}'::jsonb, now() - interval '20 minutes');
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000001105', '00000000-0000-4000-8000-000000003105', 'notice_scheduled', 'Notice queued — Notice of non-renewal — Depot Cleaning Agreement', 'Goes out in 90s unless killed.', false, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.","page":1,"start":96,"end":242,"clauseKind":"notice_period"}'::jsonb, now() - interval '20 minutes');
insert into cw_events (org_id, contract_id, signal_id, kind, title, detail, needs_you, evidence, at) values
  ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000001106', '00000000-0000-4000-8000-000000003106', 'notice_scheduled', 'Notice queued — Notice of non-renewal — Haulage Framework Agreement', 'Goes out in 90s unless killed.', false, '{"quote":"Either party may prevent renewal by giving written notice of non-renewal not less than thirty (30) days prior to the end of the then-current term.","page":1,"start":97,"end":243,"clauseKind":"notice_period"}'::jsonb, now() - interval '20 minutes');

