#!/usr/bin/env node
/* Phosphor Regular, compiled into one map so no icon font loads and nothing is fetched at
 * runtime. The set is read off @phosphor-icons/core on this machine; a name this site asks for
 * that the set does not carry throws here rather than rendering an empty box in a page. */
import fs from 'node:fs';
import path from 'node:path';

const HERE = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
/* ⛔ THE SIBLING IS FOUND BY WHAT IT CONTAINS, NEVER BY A REPO NAME THIS FILE REMEMBERS.
 * The two fallbacks below used to be spelled `partsproof-next` and `triagedesk-next`. On
 * 2026-09-14 the estate renamed every `<slug>-next` tree to `<slug>`, both paths stopped
 * existing inside the same minute, and `npm run build` threw here on a repo nobody had
 * touched: "build-icons: no Phosphor Regular set on this machine". Neither sibling had lost
 * its icons; only the spelling of where they live had moved. So this scans the estate for the
 * set and takes the first that is really there, sorted so two machines resolve the same one. */
const ESTATE = `${process.env.HOME}/CompoundLabs`;
const siblings = fs.existsSync(ESTATE)
  ? fs.readdirSync(ESTATE).sort().flatMap((d) => [
      `${ESTATE}/${d}/node_modules/@phosphor-icons/core/assets/regular`,
      `${ESTATE}/${d}/src/icons/phosphor`,
    ])
  : [];
const CANDIDATES = [`${HERE}/node_modules/@phosphor-icons/core/assets/regular`, ...siblings];
/* A directory that EXISTS is not a set that CARRIES these glyphs: several repos keep a handful
 * of traced phosphor files under src/icons/phosphor, and taking the first one that exists threw
 * "no phosphor glyph squares-four" one line further down. The probe is the first name the map
 * below asks for, so the candidate that answers is one that can answer the whole list. */
const DIR = CANDIDATES.find((d) => fs.existsSync(path.join(d, 'squares-four.svg')));
if (!DIR) throw new Error('build-icons: no Phosphor Regular set on this machine');

/* Only the glyphs this site actually asks for. The whole set is 1,512 files and shipping all of
 * them into a bundle to use thirty is the kind of weight nobody measures until it is the page. */
const WANTED = [
  /* the chrome: the two surfaces, the brand row and the folio's own facts */
  'squares-four', 'stack', 'flask', 'cube', 'pulse', 'clock', 'magnifying-glass',
  'arrow-up-right', 'caret-right', 'caret-down', 'x', 'check',
  /* the vocabulary a score is stated in: what held, what was caught, what was never run */
  'check-circle', 'x-circle', 'circle-dashed', 'shield-check', 'seal-check',
  /* what an environment is made of: seeded rows, a task, a guard, a named cheat */
  'database', 'list-checks', 'target', 'mask-happy', 'warning', 'bug',
  /* how a task is driven, and what it wrote */
  'app-window', 'terminal-window', 'rows', 'article', 'dot-outline', 'hash', 'tag',
];

const out = {};
for (const n of WANTED) {
  const f = path.join(DIR, `${n}.svg`);
  if (!fs.existsSync(f)) throw new Error(`build-icons: no phosphor glyph ${n}`);
  out[n] = fs.readFileSync(f, 'utf8')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s+/g, ' ')
    .trim();
}
fs.mkdirSync(`${HERE}/src/icons`, { recursive: true });
fs.writeFileSync(
  `${HERE}/src/icons/phosphor.generated.ts`,
  '/* GENERATED by scripts/build-icons.mjs from @phosphor-icons/core (MIT). Do not edit. */\n' +
    `export const PHOSPHOR = ${JSON.stringify(out, null, 0)} as const;\n` +
    'export type PhName = keyof typeof PHOSPHOR;\n',
);
console.log(`build-icons: ${Object.keys(out).length} glyphs`);
